"""add customer first name fields

Revision ID: 428d9ce54092
Revises: b6ab1b08707f
Create Date: 2026-08-01 16:02:37.627742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428d9ce54092'
down_revision = 'b6ab1b08707f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('doctor_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint(None, ['doctor_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('doctor_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
