"""Add payment status

Revision ID: 6c28c8a02a28
Revises: dc9c133b73a6
Create Date: 2026-07-22 16:13:21.257284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c28c8a02a28'
down_revision = 'dc9c133b73a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premium_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('premium_payments_transaction_id_key'), type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premium_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('premium_payments_transaction_id_key'), ['transaction_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('remarks')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
