"""Create customer policies table

Revision ID: a5f3ab4a5c5f
Revises: ae66f6a32117
Create Date: 2026-07-21 16:25:44.931292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f3ab4a5c5f'
down_revision = 'ae66f6a32117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('policy_start_date', sa.Date(), nullable=False),
    sa.Column('policy_end_date', sa.Date(), nullable=False),
    sa.Column('nominee_name', sa.String(length=150), nullable=False),
    sa.Column('nominee_relationship', sa.String(length=100), nullable=False),
    sa.Column('premium_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_policies')
    # ### end Alembic commands ###
