"""Create policies table

Revision ID: ae66f6a32117
Revises: 8a4b42480cef
Create Date: 2026-07-20 16:25:46.304544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae66f6a32117'
down_revision = '8a4b42480cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('policy_name', sa.String(length=150), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=True),
    sa.Column('sum_assured', sa.Float(), nullable=True),
    sa.Column('premium_amount', sa.Float(), nullable=True),
    sa.Column('premium_frequency', sa.String(length=30), nullable=True),
    sa.Column('policy_term', sa.Integer(), nullable=True),
    sa.Column('maturity_age', sa.Integer(), nullable=True),
    sa.Column('min_entry_age', sa.Integer(), nullable=True),
    sa.Column('max_entry_age', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
